### ISSUE TITLE
[2pt] Recipe app: Setup project - Group Task

### ISSUE THREAD

**Issue by zieeco** [zieeco/recipe-app#15]
- Setup the project using the `rails new App_name` command and make sure that your project has a Postgres database set up with a password.
- Install linters.
- Install RSpec gem.
- Add the bootstrap link.
- Choose font family, colors, and design layout.
- Update the readme file to be more professional.

**Comment by samiullahbahadur** [comment]
https://github.com/zieeco/recipe-app/pull/19
